dist: trusty
language: python
python: 3.5
addons:
  postgresql: 9.5
before_install:
  - sudo apt-get install postgresql-9.5-debversion
script:
  - psql -d template1 -c 'create extension hstore;' -U postgres
  - psql -d template1 -c 'create extension debversion;' -U postgres
  - psql -d template1 -c 'SHOW server_version;' -U postgres
